<header class="u-clearfix u-header u-sticky u-sticky-53ac u-header" id="header">
    <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-sheet-1">
        <a href="{{ route('home', ['locale' => app()->getLocale()]) }}" data-page-id="351725170" class="u-image u-logo u-image-1" data-image-width="500" data-image-height="500" data-lang-pt="#" data-lang-en="#" data-lang-es="#">
            <img src="{{ asset('images/9.png') }}" class="u-logo-image u-logo-image-1" title="HOME - Support Solo Sondagens">
        </a>
        <nav class="u-dropdown-icon u-menu u-menu-dropdown u-offcanvas u-menu-1" role="navigation" data-responsive-from="XS" data-position="Menu">
            <div class="menu-collapse" style="font-size: 1.125rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
                <a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-text-shadow u-custom-top-bottom-menu-spacing u-hamburger-link u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base u-text-palette-2-base" href="#" tabindex="-1" aria-label="Open menu" aria-controls="8107">
                    <svg class="u-svg-link" viewBox="0 0 24 24"><use xlink:href="#menu-hamburger"></use></svg>
                    <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect></g></svg>
                </a>
            </div>
            <div class="u-custom-menu u-nav-container">
                <ul role="menubar" class="u-nav u-spacing-30 u-unstyled u-nav-1">
                    <li role="none" class="u-nav-item">
                        <a role="menuitem" class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS&quot;}" data-lang-en="{&quot;content&quot;:&quot;SERVICES&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS&quot;}" style="padding: 10px 0px;">SERVIÇOS</a>
                        <div class="u-nav-popup">
                            <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-2" aria-label="SERVIÇOS menu">
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.geological', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS GEOLÓGICOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;GEOLOGICAL SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS GEOLÓGICOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}">SERVIÇOS GEOLÓGICOS</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.laboratory', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS LABORATORIAIS&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;LABORATORY SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS LABORATORIALES&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}">SERVIÇOS LABORATORIAIS</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.special-drilling', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SONDAGEM ESPECIAIS&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SPECIAL DRILLING&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SONDEO ESPECIALES&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}">SONDAGEM ESPECIAIS</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.project-development', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS ELABORARAÇÃO DE COMPLEMENTARES&quot;,&quot;href&quot;:&quot;Serviços-Elaboração-Projetos.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SERVICES FOR DEVELOPING COMPLEMENTARIES&quot;,&quot;href&quot;:&quot;Serviços-Elaboração-Projetos.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS ELABORACIÓN DE COMPLEMENTARIOS&quot;,&quot;href&quot;:&quot;Serviços-Elaboração-Projetos.html&quot;}">SERVIÇOS ELABORARAÇÃO DE COMPLEMENTARES</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.deep-foundation', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS DE FUNDAÇÃO PROFUNDA&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;DEEP FOUNDATION SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS DE FUNDACIÓN PROFUNDA&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}">SERVIÇOS DE FUNDAÇÃO PROFUNDA</a></li>
                            </ul>
                        </div>
                    </li>
                    <li role="none" class="u-nav-item">
                        <a role="menuitem" class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('services.geological', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;PORTFOLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" style="padding: 10px 0px;">PORTFÓLIOS</a>
                        <div class="u-nav-popup">
                            <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-3" aria-label="PORTFÓLIOS menu">
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('portfolio.soil', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO SOLO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SOIL PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE SUELO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}">PORTFÓLIO SOLO</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('portfolio.mining', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO MINERAÇÃO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;MINING PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE MINERÍA&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}">PORTFÓLIO MINERAÇÃO</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('portfolio.transmission', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO TRANSMISSORAS&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;TRANSMISSION PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE TRANSMISORAS&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}">PORTFÓLIO TRANSMISSORAS</a></li>
                            </ul>
                        </div>
                    </li>
                    <li role="none" class="u-nav-item"><a role="menuitem" class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://app.supportsondagens.com.br/index.php/signin" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;ÁREA DO CLIENTE&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}" data-lang-en="{&quot;content&quot;:&quot;CLIENT AREA&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}" data-lang-es="{&quot;content&quot;:&quot;ÁREA DEL CLIENTE&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}" style="padding: 10px 0px;">ÁREA DO CLIENTE</a></li>
                    <li role="none" class="u-nav-item"><a role="menuitem" class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="{{ route('report', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;DENÚNCIE&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;REPORT&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;DENUNCIA&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}" style="padding: 10px 0px;">DENÚNCIE</a></li>
                    <li role="none" class="u-nav-item">
                        <a role="menuitem" class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" data-lang-pt="{&quot;content&quot;:&quot;COLABORADORES&quot;}" data-lang-en="{&quot;content&quot;:&quot;COLLABORATORS&quot;}" data-lang-es="{&quot;content&quot;:&quot;COLABORADORES&quot;}" style="padding: 10px 0px;">COLABORADORES</a>
                        <div class="u-nav-popup">
                            <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-4" aria-label="COLABORADORES menu">
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://www.spt.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;SISTEMA SONDAGEM&quot;}" data-lang-en="{&quot;content&quot;:&quot;DRILLING SYSTEM&quot;}" data-lang-es="{&quot;content&quot;:&quot;SISTEMA DE SONDEO&quot;}">SONDAGEM</a></li>
                                <li role="none" class="u-nav-item"><a tabindex="-1" role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://www.sev.supportsondagens.com.br" target="_blank">SONDAGEM ELÉTRICA</a></li>
                                <li role="none" class="u-nav-item"><a tabindex="-1" role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://www.sesmt.supportsondagens.com.br" target="_blank">CONTROLE MÉDICINA DO TRABALHO</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://www.ponto.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;PONTO ELETRÔNICO&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}" data-lang-en="{&quot;content&quot;:&quot;ELECTRONIC POINT&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}" data-lang-es="{&quot;content&quot;:&quot;PUNTO ELECTRÓNICO&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}">PONTO ELETRÔNICO</a></li>
                                <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link u-text-active-palette-2-base u-text-hover-palette-1-base u-text-palette-2-base" href="https://www.webmail.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;WEBMAIL&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}" data-lang-en="{&quot;content&quot;:&quot;WEBMAIL&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}" data-lang-es="{&quot;content&quot;:&quot;CORREO ELECTRÓNICO&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}">WEBMAIL</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="u-custom-menu u-nav-container-collapse" id="8107" role="region" aria-label="Menu panel">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                    <div class="u-inner-container-layout u-sidenav-overflow">
                        <div class="u-menu-close" tabindex="-1" aria-label="Close menu"></div>
                        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-5" role="menubar">
                            <li role="none" class="u-nav-item">
                                <a role="menuitem" class="u-button-style u-nav-link" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS&quot;}" data-lang-en="{&quot;content&quot;:&quot;SERVICES&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS&quot;}">SERVIÇOS</a>
                                <div class="u-nav-popup">
                                    <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-6" aria-label="SERVIÇOS menu">
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.geological', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS GEOLÓGICOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;GEOLOGICAL SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS GEOLÓGICOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}">SERVIÇOS GEOLÓGICOS</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.laboratory', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS LABORATORIAIS&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;LABORATORY SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS LABORATORIALES&quot;,&quot;href&quot;:&quot;Serviços-Laboratorial.html&quot;}">SERVIÇOS LABORATORIAIS</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.special-drilling', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SONDAGEM ESPECIAIS&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SPECIAL DRILLING&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SONDEO ESPECIALES&quot;,&quot;href&quot;:&quot;Sondagem-Sondas-Especiais.html&quot;}">SONDAGEM ESPECIAIS</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.project-development', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS ELABORARAÇÃO DE COMPLEMENTARES&quot;,&quot;href&quot;:&quot;Serviços-Elaboração-Projetos.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SERVICES FOR DEVELOPING COMPLEMENTARIES&quot;,&quot;href&quot;:&quot;Serviços-Elaboração-Projetos.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS ELABORACIÓN DE COMPLEMENTARIOS&quot;,&quot;href&quot;:&quot;Serviços-Elaboración-Projetos.html&quot;}">SERVIÇOS ELABORARAÇÃO DE COMPLEMENTARES</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.deep-foundation', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;SERVIÇOS DE FUNDAÇÃO PROFUNDA&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;DEEP FOUNDATION SERVICES&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;SERVICIOS DE FUNDACIÓN PROFUNDA&quot;,&quot;href&quot;:&quot;Serviços-Fundação-Profunda.html&quot;}">SERVIÇOS DE FUNDAÇÃO PROFUNDA</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li role="none" class="u-nav-item">
                                <a role="menuitem" class="u-button-style u-nav-link" href="{{ route('services.geological', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;PORTFOLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIOS&quot;,&quot;href&quot;:&quot;Serviços-Geológico.html&quot;}">PORTFÓLIOS</a>
                                <div class="u-nav-popup">
                                    <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-7" aria-label="PORTFÓLIOS menu">
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('portfolio.soil', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO SOLO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;SOIL PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE SUELO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Geológicos.html&quot;}">PORTFÓLIO SOLO</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('portfolio.mining', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO MINERAÇÃO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;MINING PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE MINERÍA&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Mineração.html&quot;}">PORTFÓLIO MINERAÇÃO</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('portfolio.transmission', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;PORTFÓLIO TRANSMISSORAS&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;TRANSMISSION PORTFOLIO&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;PORTFOLIO DE TRANSMISORAS&quot;,&quot;href&quot;:&quot;Portfólio-Serviços-Transmissão.html&quot;}">PORTFÓLIO TRANSMISSORAS</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="https://app.supportsondagens.com.br/index.php/signin" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;ÁREA DO CLIENTE&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}" data-lang-en="{&quot;content&quot;:&quot;CLIENT AREA&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}" data-lang-es="{&quot;content&quot;:&quot;ÁREA DEL CLIENTE&quot;,&quot;href&quot;:&quot;https://app.supportsondagens.com.br/index.php/signin&quot;}">ÁREA DO CLIENTE</a></li>
                            <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="{{ route('report', ['locale' => app()->getLocale()]) }}" data-lang-pt="{&quot;content&quot;:&quot;DENÚNCIE&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}" data-lang-en="{&quot;content&quot;:&quot;REPORT&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}" data-lang-es="{&quot;content&quot;:&quot;DENUNCIA&quot;,&quot;href&quot;:&quot;Formulario-de-Denúncia.html&quot;}">DENÚNCIE</a></li>
                            <li role="none" class="u-nav-item">
                                <a role="menuitem" class="u-button-style u-nav-link" data-lang-pt="{&quot;content&quot;:&quot;COLABORADORES&quot;}" data-lang-en="{&quot;content&quot;:&quot;COLLABORATORS&quot;}" data-lang-es="{&quot;content&quot;:&quot;COLABORADORES&quot;}">COLABORADORES</a>
                                <div class="u-nav-popup">
                                    <ul role="menu" class="u-h-spacing-20 u-nav u-unstyled u-v-spacing-10 u-nav-8" aria-label="COLABORADORES menu">
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="https://www.spt.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;SISTEMA SONDAGEM&quot;}" data-lang-en="{&quot;content&quot;:&quot;DRILLING SYSTEM&quot;}" data-lang-es="{&quot;content&quot;:&quot;SISTEMA DE SONDEO&quot;}">SONDAGEM</a></li>
                                        <li role="none" class="u-nav-item"><a tabindex="-1" role="menuitem" class="u-button-style u-nav-link" href="https://www.sev.supportsondagens.com.br" target="_blank">SONDAGEM ELÉTRICA</a></li>
                                        <li role="none" class="u-nav-item"><a tabindex="-1" role="menuitem" class="u-button-style u-nav-link" href="https://www.sesmt.supportsondagens.com.br" target="_blank">CONTROLE MÉDICINA DO TRABALHO</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="https://www.ponto.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;PONTO ELETRÔNICO&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}" data-lang-en="{&quot;content&quot;:&quot;ELECTRONIC POINT&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}" data-lang-es="{&quot;content&quot;:&quot;PUNTO ELECTRÓNICO&quot;,&quot;href&quot;:&quot;https://www.ponto.supportsondagens.com.br&quot;}">PONTO ELETRÔNICO</a></li>
                                        <li role="none" class="u-nav-item"><a role="menuitem" class="u-button-style u-nav-link" href="https://www.webmail.supportsondagens.com.br" target="_blank" data-lang-pt="{&quot;content&quot;:&quot;WEBMAIL&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}" data-lang-en="{&quot;content&quot;:&quot;WEBMAIL&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}" data-lang-es="{&quot;content&quot;:&quot;CORREO ELECTRÓNICO&quot;,&quot;href&quot;:&quot;https://www.webmail.supportsondagens.com.br&quot;}">WEBMAIL</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
            </div>
            <style class="menu-style">@media (max-width: 539px) {
                [data-responsive-from="XS"] .u-nav-container {
                    display: none;
                }
                [data-responsive-from="XS"] .menu-collapse {
                    display: block;
                }
            }</style>
        </nav>
        <div class="u-language u-language-content-icon-text u-language-layout-icons u-spacing-10 u-language-1">
            <a class="u-language-top-url u-language-url u-text-black" data-lang-text="Português" href="{{ route('home', ['locale' => 'pt']) }}" data-language="pt" style="background-image: none; text-transform: uppercase; font-size: 0.75rem;"><span class="u-file-icon u-icon u-language-icon u-language-pt u-icon-1"><img src="{{ asset('images/icone18.png') }}" alt=""></span></a>
            <a class="u-language-top-url u-language-url u-text-black" data-lang-text="English" href="{{ route('home', ['locale' => 'en']) }}" data-language="en" style="background-image: none; text-transform: uppercase; font-size: 0.75rem;"><span class="u-file-icon u-icon u-language-en u-language-icon u-icon-2"><img src="{{ asset('images/icone19.png') }}" alt=""></span></a>
            <a class="u-language-top-url u-language-url u-text-black" data-lang-text="Español" href="{{ route('home', ['locale' => 'es']) }}" data-language="es" style="background-image: none; text-transform: uppercase; font-size: 0.75rem;"><span class="u-file-icon u-icon u-language-es u-language-icon u-icon-3"><img src="{{ asset('images/icone20.png') }}" alt=""></span></a>
        </div>
    </div>
</header>
