<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Nicepage Routes
|--------------------------------------------------------------------------
|
| Auto-generated routes for Nicepage HTML pages converted to Blade views.
| Generated on: 2026-02-08 16:08:45
|
*/

// Root redirect
Route::get('/', function () {
    return redirect()->route('pt.pagina-1');
})->name('home');

// Portuguese Routes
Route::prefix('pt')->name('pt.')->group(function () {
    Route::get('acessibilidade', fn() => view('pt.acessibilidade'))->name('acessibilidade');
    Route::get('adensamento', fn() => view('pt.adensamento'))->name('adensamento');
    Route::get('amostra-tipo-bloco', fn() => view('pt.amostra-tipo-bloco'))->name('amostra-tipo-bloco');
    Route::get('amostra-tipo-denison', fn() => view('pt.amostra-tipo-denison'))->name('amostra-tipo-denison');
    Route::get('amostra-tipo-shelby', fn() => view('pt.amostra-tipo-shelby'))->name('amostra-tipo-shelby');
    Route::get('aquecimento', fn() => view('pt.aquecimento'))->name('aquecimento');
    Route::get('bloqueamento-de-pavimento', fn() => view('pt.bloqueamento-de-pavimento'))->name('bloqueamento-de-pavimento');
    Route::get('canteiro-de-obra', fn() => view('pt.canteiro-de-obra'))->name('canteiro-de-obra');
    Route::get('cbr-e-expancao', fn() => view('pt.cbr-e-expancao'))->name('cbr-e-expancao');
    Route::get('cisalhamento-direto', fn() => view('pt.cisalhamento-direto'))->name('cisalhamento-direto');
    Route::get('climatizacao', fn() => view('pt.climatizacao'))->name('climatizacao');
    Route::get('codigo-de-tica-e-conduta', fn() => view('pt.codigo-de-tica-e-conduta'))->name('codigo-de-tica-e-conduta');
    Route::get('codigo-de-etica-e-conduta', fn() => view('pt.codigo-de-tica-e-conduta'))->name('codigo-de-etica-e-conduta');
    Route::get('combate-a-incendio', fn() => view('pt.combate-a-incendio'))->name('combate-a-incendio');
    Route::get('compactacao', fn() => view('pt.compactacao'))->name('compactacao');
    Route::get('concreto-armado', fn() => view('pt.concreto-armado'))->name('concreto-armado');
    Route::get('concreto-protendido', fn() => view('pt.concreto-protendido'))->name('concreto-protendido');
    Route::get('demolicao', fn() => view('pt.demolicao'))->name('demolicao');
    Route::get('dosagem', fn() => view('pt.dosagem'))->name('dosagem');
    Route::get('drenagem', fn() => view('pt.drenagem'))->name('drenagem');
    Route::get('eletrica-de-baixa-tensao', fn() => view('pt.eletrica-de-baixa-tensao'))->name('eletrica-de-baixa-tensao');
    Route::get('ensaio-ph-laboratorial', fn() => view('pt.ensaio-ph-laboratorial'))->name('ensaio-ph-laboratorial');
    Route::get('ensaios-especiais-eletricos', fn() => view('pt.ensaios-especiais-eletricos'))->name('ensaios-especiais-eletricos');
    Route::get('estaca-escavada', fn() => view('pt.estaca-escavada'))->name('estaca-escavada');
    Route::get('estrutura-metalica', fn() => view('pt.estrutura-metalica'))->name('estrutura-metalica');
    Route::get('formulario-de-denuncia', fn() => view('pt.formulario-de-denuncia'))->name('formulario-de-denuncia');
    Route::get('fundacoes', fn() => view('pt.fundacoes'))->name('fundacoes');
    Route::get('gas-liquefeito-de-petroleo', fn() => view('pt.gas-liquefeito-de-petroleo'))->name('gas-liquefeito-de-petroleo');
    Route::get('gases-medicinais', fn() => view('pt.gases-medicinais'))->name('gases-medicinais');
    Route::get('granulometria-por-peneiramento', fn() => view('pt.granulometria-por-peneiramento'))->name('granulometria-por-peneiramento');
    Route::get('granulometria-por-sedimentacao', fn() => view('pt.granulometria-por-sedimentacao'))->name('granulometria-por-sedimentacao');
    Route::get('helice-continua', fn() => view('pt.helice-continua'))->name('helice-continua');
    Route::get('hidrossanitarios', fn() => view('pt.hidrossanitarios'))->name('hidrossanitarios');
    Route::get('home-support-solo-sondagens', fn() => view('pt.home-support-solo-sondagens'))->name('home-support-solo-sondagens');
    Route::get('inclinometro', fn() => view('pt.inclinometro'))->name('inclinometro');
    Route::get('index', fn() => view('pt.index'))->name('index');
    Route::get('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a', fn() => view('pt.intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a'))->name('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a');
    Route::get('intranet', fn() => view('pt.intranet'))->name('intranet');
    Route::get('limite-de-liquidez', fn() => view('pt.limite-de-liquidez'))->name('limite-de-liquidez');
    Route::get('limite-de-pasticidade', fn() => view('pt.limite-de-pasticidade'))->name('limite-de-pasticidade');
    Route::get('logica-e-telefonia', fn() => view('pt.logica-e-telefonia'))->name('logica-e-telefonia');
    Route::get('marcos-de-referencia', fn() => view('pt.marcos-de-referencia'))->name('marcos-de-referencia');
    Route::get('massa-especifica-dos-graos', fn() => view('pt.massa-especifica-dos-graos'))->name('massa-especifica-dos-graos');
    Route::get('mct-compactacao', fn() => view('pt.mct-compactacao'))->name('mct-compactacao');
    Route::get('mct-pastilha', fn() => view('pt.mct-pastilha'))->name('mct-pastilha');
    Route::get('medicao-de-ph-in-situ', fn() => view('pt.medicao-de-ph-in-situ'))->name('medicao-de-ph-in-situ');
    Route::get('medidores-de-vazao', fn() => view('pt.medidores-de-vazao'))->name('medidores-de-vazao');
    Route::get('missao-valores-e-objetivos', fn() => view('pt.missao-valores-e-objetivos'))->name('missao-valores-e-objetivos');
    Route::get('monitoramento-e-seguranca', fn() => view('pt.monitoramento-e-seguranca'))->name('monitoramento-e-seguranca');
    Route::get('pagina-1', fn() => view('pt.pagina-1'))->name('pagina-1');
    Route::get('paisagismo', fn() => view('pt.paisagismo'))->name('paisagismo');
    Route::get('piezometro', fn() => view('pt.piezometro'))->name('piezometro');
    Route::get('plano-de-seguranca-do-trabalho', fn() => view('pt.plano-de-seguranca-do-trabalho'))->name('plano-de-seguranca-do-trabalho');
    Route::get('poco-de-inspecao-de-pavimento', fn() => view('pt.poco-de-inspecao-de-pavimento'))->name('poco-de-inspecao-de-pavimento');
    Route::get('poco-de-monitoramento', fn() => view('pt.poco-de-monitoramento'))->name('poco-de-monitoramento');
    Route::get('politica-anticorrupcao', fn() => view('pt.politica-anticorrupcao'))->name('politica-anticorrupcao');
    Route::get('politica-de-anti-assedio', fn() => view('pt.politica-de-anti-assedio'))->name('politica-de-anti-assedio');
    Route::get('politica-de-assedio-moral', fn() => view('pt.politica-de-assedio-moral'))->name('politica-de-assedio-moral');
    Route::get('politica-de-dados', fn() => view('pt.politica-de-dados'))->name('politica-de-dados');
    Route::get('politica-de-gestao-ambiental', fn() => view('pt.politica-de-gestao-ambiental'))->name('politica-de-gestao-ambiental');
    Route::get('politica-de-qualidade', fn() => view('pt.politica-de-qualidade'))->name('politica-de-qualidade');
    Route::get('portfolio-servicos-geologicos', fn() => view('pt.portfolio-servicos-geologicos'))->name('portfolio-servicos-geologicos');
    Route::get('portfolio-servicos-mineracao', fn() => view('pt.portfolio-servicos-mineracao'))->name('portfolio-servicos-mineracao');
    Route::get('portfolio-servicos-transmissao', fn() => view('pt.portfolio-servicos-transmissao'))->name('portfolio-servicos-transmissao');
    Route::get('resistividade-de-pe-de-torre', fn() => view('pt.resistividade-de-pe-de-torre'))->name('resistividade-de-pe-de-torre');
    Route::get('resistividade-termica-do-solo', fn() => view('pt.resistividade-termica-do-solo'))->name('resistividade-termica-do-solo');
    Route::get('retrofit-engenharia', fn() => view('pt.retrofit-engenharia'))->name('retrofit-engenharia');
    Route::get('servicos-elaboracao-projetos', fn() => view('pt.servicos-elaboracao-projetos'))->name('servicos-elaboracao-projetos');
    Route::get('servicos-fundacao-profunda', fn() => view('pt.servicos-fundacao-profunda'))->name('servicos-fundacao-profunda');
    Route::get('servicos-geologico', fn() => view('pt.servicos-geologico'))->name('servicos-geologico');
    Route::get('servicos-laboratorial', fn() => view('pt.servicos-laboratorial'))->name('servicos-laboratorial');
    Route::get('sinalizacao', fn() => view('pt.sinalizacao'))->name('sinalizacao');
    Route::get('som-tv-e-acustica', fn() => view('pt.som-tv-e-acustica'))->name('som-tv-e-acustica');
    Route::get('sonda-de-polarizacao', fn() => view('pt.sonda-de-polarizacao'))->name('sonda-de-polarizacao');
    Route::get('sonda-eletrica-focada', fn() => view('pt.sonda-eletrica-focada'))->name('sonda-eletrica-focada');
    Route::get('sonda-gama-natural', fn() => view('pt.sonda-gama-natural'))->name('sonda-gama-natural');
    Route::get('sonda-para-desvio-de-poco', fn() => view('pt.sonda-para-desvio-de-poco'))->name('sonda-para-desvio-de-poco');
    Route::get('sonda-raio-gama', fn() => view('pt.sonda-raio-gama'))->name('sonda-raio-gama');
    Route::get('sondagem-a-percussao', fn() => view('pt.sondagem-a-percussao'))->name('sondagem-a-percussao');
    Route::get('sondagem-a-trado', fn() => view('pt.sondagem-a-trado'))->name('sondagem-a-trado');
    Route::get('sondagem-eletrica-vertical', fn() => view('pt.sondagem-eletrica-vertical'))->name('sondagem-eletrica-vertical');
    Route::get('sondagem-flutuante', fn() => view('pt.sondagem-flutuante'))->name('sondagem-flutuante');
    Route::get('sondagem-manual', fn() => view('pt.sondagem-manual'))->name('sondagem-manual');
    Route::get('sondagem-mista', fn() => view('pt.sondagem-mista'))->name('sondagem-mista');
    Route::get('sondagem-rotativa', fn() => view('pt.sondagem-rotativa'))->name('sondagem-rotativa');
    Route::get('sondagem-rotopercussiva', fn() => view('pt.sondagem-rotopercussiva'))->name('sondagem-rotopercussiva');
    Route::get('sondagem-sondas-especiais', fn() => view('pt.sondagem-sondas-especiais'))->name('sondagem-sondas-especiais');
    Route::get('spda', fn() => view('pt.spda'))->name('spda');
    Route::get('speedy', fn() => view('pt.speedy'))->name('speedy');
    Route::get('termo-de-servicos', fn() => view('pt.termo-de-servicos'))->name('termo-de-servicos');
    Route::get('triaxial', fn() => view('pt.triaxial'))->name('triaxial');
    Route::get('vane-test-ensaio-de-palheta', fn() => view('pt.vane-test-ensaio-de-palheta'))->name('vane-test-ensaio-de-palheta');
    Route::get('visita-tecnica-engenharia', fn() => view('pt.visita-tecnica-engenharia'))->name('visita-tecnica-engenharia');
});

// English Routes
Route::prefix('en')->name('en.')->group(function () {
    Route::get('acessibilidade', fn() => view('en.acessibilidade'))->name('acessibilidade');
    Route::get('adensamento', fn() => view('en.adensamento'))->name('adensamento');
    Route::get('amostra-tipo-bloco', fn() => view('en.amostra-tipo-bloco'))->name('amostra-tipo-bloco');
    Route::get('amostra-tipo-denison', fn() => view('en.amostra-tipo-denison'))->name('amostra-tipo-denison');
    Route::get('amostra-tipo-shelby', fn() => view('en.amostra-tipo-shelby'))->name('amostra-tipo-shelby');
    Route::get('aquecimento', fn() => view('en.aquecimento'))->name('aquecimento');
    Route::get('bloqueamento-de-pavimento', fn() => view('en.bloqueamento-de-pavimento'))->name('bloqueamento-de-pavimento');
    Route::get('canteiro-de-obra', fn() => view('en.canteiro-de-obra'))->name('canteiro-de-obra');
    Route::get('cbr-e-expancao', fn() => view('en.cbr-e-expancao'))->name('cbr-e-expancao');
    Route::get('cisalhamento-direto', fn() => view('en.cisalhamento-direto'))->name('cisalhamento-direto');
    Route::get('climatizacao', fn() => view('en.climatizacao'))->name('climatizacao');
    Route::get('codigo-de-tica-e-conduta', fn() => view('en.codigo-de-tica-e-conduta'))->name('codigo-de-tica-e-conduta');
    Route::get('codigo-de-etica-e-conduta', fn() => view('en.codigo-de-tica-e-conduta'))->name('codigo-de-etica-e-conduta');
    Route::get('combate-a-incendio', fn() => view('en.combate-a-incendio'))->name('combate-a-incendio');
    Route::get('compactacao', fn() => view('en.compactacao'))->name('compactacao');
    Route::get('concreto-armado', fn() => view('en.concreto-armado'))->name('concreto-armado');
    Route::get('concreto-protendido', fn() => view('en.concreto-protendido'))->name('concreto-protendido');
    Route::get('demolicao', fn() => view('en.demolicao'))->name('demolicao');
    Route::get('dosagem', fn() => view('en.dosagem'))->name('dosagem');
    Route::get('drenagem', fn() => view('en.drenagem'))->name('drenagem');
    Route::get('eletrica-de-baixa-tensao', fn() => view('en.eletrica-de-baixa-tensao'))->name('eletrica-de-baixa-tensao');
    Route::get('ensaio-ph-laboratorial', fn() => view('en.ensaio-ph-laboratorial'))->name('ensaio-ph-laboratorial');
    Route::get('ensaios-especiais-eletricos', fn() => view('en.ensaios-especiais-eletricos'))->name('ensaios-especiais-eletricos');
    Route::get('estaca-escavada', fn() => view('en.estaca-escavada'))->name('estaca-escavada');
    Route::get('estrutura-metalica', fn() => view('en.estrutura-metalica'))->name('estrutura-metalica');
    Route::get('formulario-de-denuncia', fn() => view('en.formulario-de-denuncia'))->name('formulario-de-denuncia');
    Route::get('fundacoes', fn() => view('en.fundacoes'))->name('fundacoes');
    Route::get('gas-liquefeito-de-petroleo', fn() => view('en.gas-liquefeito-de-petroleo'))->name('gas-liquefeito-de-petroleo');
    Route::get('gases-medicinais', fn() => view('en.gases-medicinais'))->name('gases-medicinais');
    Route::get('granulometria-por-peneiramento', fn() => view('en.granulometria-por-peneiramento'))->name('granulometria-por-peneiramento');
    Route::get('granulometria-por-sedimentacao', fn() => view('en.granulometria-por-sedimentacao'))->name('granulometria-por-sedimentacao');
    Route::get('helice-continua', fn() => view('en.helice-continua'))->name('helice-continua');
    Route::get('hidrossanitarios', fn() => view('en.hidrossanitarios'))->name('hidrossanitarios');
    Route::get('home-support-solo-sondagens', fn() => view('en.home-support-solo-sondagens'))->name('home-support-solo-sondagens');
    Route::get('inclinometro', fn() => view('en.inclinometro'))->name('inclinometro');
    Route::get('index', fn() => view('en.index'))->name('index');
    Route::get('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a', fn() => view('en.intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a'))->name('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a');
    Route::get('intranet', fn() => view('en.intranet'))->name('intranet');
    Route::get('limite-de-liquidez', fn() => view('en.limite-de-liquidez'))->name('limite-de-liquidez');
    Route::get('limite-de-pasticidade', fn() => view('en.limite-de-pasticidade'))->name('limite-de-pasticidade');
    Route::get('logica-e-telefonia', fn() => view('en.logica-e-telefonia'))->name('logica-e-telefonia');
    Route::get('marcos-de-referencia', fn() => view('en.marcos-de-referencia'))->name('marcos-de-referencia');
    Route::get('massa-especifica-dos-graos', fn() => view('en.massa-especifica-dos-graos'))->name('massa-especifica-dos-graos');
    Route::get('mct-compactacao', fn() => view('en.mct-compactacao'))->name('mct-compactacao');
    Route::get('mct-pastilha', fn() => view('en.mct-pastilha'))->name('mct-pastilha');
    Route::get('medicao-de-ph-in-situ', fn() => view('en.medicao-de-ph-in-situ'))->name('medicao-de-ph-in-situ');
    Route::get('medidores-de-vazao', fn() => view('en.medidores-de-vazao'))->name('medidores-de-vazao');
    Route::get('missao-valores-e-objetivos', fn() => view('en.missao-valores-e-objetivos'))->name('missao-valores-e-objetivos');
    Route::get('monitoramento-e-seguranca', fn() => view('en.monitoramento-e-seguranca'))->name('monitoramento-e-seguranca');
    Route::get('pagina-1', fn() => view('en.pagina-1'))->name('pagina-1');
    Route::get('paisagismo', fn() => view('en.paisagismo'))->name('paisagismo');
    Route::get('piezometro', fn() => view('en.piezometro'))->name('piezometro');
    Route::get('plano-de-seguranca-do-trabalho', fn() => view('en.plano-de-seguranca-do-trabalho'))->name('plano-de-seguranca-do-trabalho');
    Route::get('poco-de-inspecao-de-pavimento', fn() => view('en.poco-de-inspecao-de-pavimento'))->name('poco-de-inspecao-de-pavimento');
    Route::get('poco-de-monitoramento', fn() => view('en.poco-de-monitoramento'))->name('poco-de-monitoramento');
    Route::get('politica-anticorrupcao', fn() => view('en.politica-anticorrupcao'))->name('politica-anticorrupcao');
    Route::get('politica-de-anti-assedio', fn() => view('en.politica-de-anti-assedio'))->name('politica-de-anti-assedio');
    Route::get('politica-de-assedio-moral', fn() => view('en.politica-de-assedio-moral'))->name('politica-de-assedio-moral');
    Route::get('politica-de-dados', fn() => view('en.politica-de-dados'))->name('politica-de-dados');
    Route::get('politica-de-gestao-ambiental', fn() => view('en.politica-de-gestao-ambiental'))->name('politica-de-gestao-ambiental');
    Route::get('politica-de-qualidade', fn() => view('en.politica-de-qualidade'))->name('politica-de-qualidade');
    Route::get('portfolio-servicos-geologicos', fn() => view('en.portfolio-servicos-geologicos'))->name('portfolio-servicos-geologicos');
    Route::get('portfolio-servicos-mineracao', fn() => view('en.portfolio-servicos-mineracao'))->name('portfolio-servicos-mineracao');
    Route::get('portfolio-servicos-transmissao', fn() => view('en.portfolio-servicos-transmissao'))->name('portfolio-servicos-transmissao');
    Route::get('resistividade-de-pe-de-torre', fn() => view('en.resistividade-de-pe-de-torre'))->name('resistividade-de-pe-de-torre');
    Route::get('resistividade-termica-do-solo', fn() => view('en.resistividade-termica-do-solo'))->name('resistividade-termica-do-solo');
    Route::get('retrofit-engenharia', fn() => view('en.retrofit-engenharia'))->name('retrofit-engenharia');
    Route::get('servicos-elaboracao-projetos', fn() => view('en.servicos-elaboracao-projetos'))->name('servicos-elaboracao-projetos');
    Route::get('servicos-fundacao-profunda', fn() => view('en.servicos-fundacao-profunda'))->name('servicos-fundacao-profunda');
    Route::get('servicos-geologico', fn() => view('en.servicos-geologico'))->name('servicos-geologico');
    Route::get('servicos-laboratorial', fn() => view('en.servicos-laboratorial'))->name('servicos-laboratorial');
    Route::get('sinalizacao', fn() => view('en.sinalizacao'))->name('sinalizacao');
    Route::get('som-tv-e-acustica', fn() => view('en.som-tv-e-acustica'))->name('som-tv-e-acustica');
    Route::get('sonda-de-polarizacao', fn() => view('en.sonda-de-polarizacao'))->name('sonda-de-polarizacao');
    Route::get('sonda-eletrica-focada', fn() => view('en.sonda-eletrica-focada'))->name('sonda-eletrica-focada');
    Route::get('sonda-gama-natural', fn() => view('en.sonda-gama-natural'))->name('sonda-gama-natural');
    Route::get('sonda-para-desvio-de-poco', fn() => view('en.sonda-para-desvio-de-poco'))->name('sonda-para-desvio-de-poco');
    Route::get('sonda-raio-gama', fn() => view('en.sonda-raio-gama'))->name('sonda-raio-gama');
    Route::get('sondagem-a-percussao', fn() => view('en.sondagem-a-percussao'))->name('sondagem-a-percussao');
    Route::get('sondagem-a-trado', fn() => view('en.sondagem-a-trado'))->name('sondagem-a-trado');
    Route::get('sondagem-eletrica-vertical', fn() => view('en.sondagem-eletrica-vertical'))->name('sondagem-eletrica-vertical');
    Route::get('sondagem-flutuante', fn() => view('en.sondagem-flutuante'))->name('sondagem-flutuante');
    Route::get('sondagem-manual', fn() => view('en.sondagem-manual'))->name('sondagem-manual');
    Route::get('sondagem-mista', fn() => view('en.sondagem-mista'))->name('sondagem-mista');
    Route::get('sondagem-rotativa', fn() => view('en.sondagem-rotativa'))->name('sondagem-rotativa');
    Route::get('sondagem-rotopercussiva', fn() => view('en.sondagem-rotopercussiva'))->name('sondagem-rotopercussiva');
    Route::get('sondagem-sondas-especiais', fn() => view('en.sondagem-sondas-especiais'))->name('sondagem-sondas-especiais');
    Route::get('spda', fn() => view('en.spda'))->name('spda');
    Route::get('speedy', fn() => view('en.speedy'))->name('speedy');
    Route::get('termo-de-servicos', fn() => view('en.termo-de-servicos'))->name('termo-de-servicos');
    Route::get('triaxial', fn() => view('en.triaxial'))->name('triaxial');
    Route::get('vane-test-ensaio-de-palheta', fn() => view('en.vane-test-ensaio-de-palheta'))->name('vane-test-ensaio-de-palheta');
    Route::get('visita-tecnica-engenharia', fn() => view('en.visita-tecnica-engenharia'))->name('visita-tecnica-engenharia');
});

// Spanish Routes
Route::prefix('es')->name('es.')->group(function () {
    Route::get('acessibilidade', fn() => view('es.acessibilidade'))->name('acessibilidade');
    Route::get('adensamento', fn() => view('es.adensamento'))->name('adensamento');
    Route::get('amostra-tipo-bloco', fn() => view('es.amostra-tipo-bloco'))->name('amostra-tipo-bloco');
    Route::get('amostra-tipo-denison', fn() => view('es.amostra-tipo-denison'))->name('amostra-tipo-denison');
    Route::get('amostra-tipo-shelby', fn() => view('es.amostra-tipo-shelby'))->name('amostra-tipo-shelby');
    Route::get('aquecimento', fn() => view('es.aquecimento'))->name('aquecimento');
    Route::get('bloqueamento-de-pavimento', fn() => view('es.bloqueamento-de-pavimento'))->name('bloqueamento-de-pavimento');
    Route::get('canteiro-de-obra', fn() => view('es.canteiro-de-obra'))->name('canteiro-de-obra');
    Route::get('cbr-e-expancao', fn() => view('es.cbr-e-expancao'))->name('cbr-e-expancao');
    Route::get('cisalhamento-direto', fn() => view('es.cisalhamento-direto'))->name('cisalhamento-direto');
    Route::get('climatizacao', fn() => view('es.climatizacao'))->name('climatizacao');
    Route::get('codigo-de-tica-e-conduta', fn() => view('es.codigo-de-tica-e-conduta'))->name('codigo-de-tica-e-conduta');
    Route::get('codigo-de-etica-e-conduta', fn() => view('es.codigo-de-tica-e-conduta'))->name('codigo-de-etica-e-conduta');
    Route::get('combate-a-incendio', fn() => view('es.combate-a-incendio'))->name('combate-a-incendio');
    Route::get('compactacao', fn() => view('es.compactacao'))->name('compactacao');
    Route::get('concreto-armado', fn() => view('es.concreto-armado'))->name('concreto-armado');
    Route::get('concreto-protendido', fn() => view('es.concreto-protendido'))->name('concreto-protendido');
    Route::get('demolicao', fn() => view('es.demolicao'))->name('demolicao');
    Route::get('dosagem', fn() => view('es.dosagem'))->name('dosagem');
    Route::get('drenagem', fn() => view('es.drenagem'))->name('drenagem');
    Route::get('eletrica-de-baixa-tensao', fn() => view('es.eletrica-de-baixa-tensao'))->name('eletrica-de-baixa-tensao');
    Route::get('ensaio-ph-laboratorial', fn() => view('es.ensaio-ph-laboratorial'))->name('ensaio-ph-laboratorial');
    Route::get('ensaios-especiais-eletricos', fn() => view('es.ensaios-especiais-eletricos'))->name('ensaios-especiais-eletricos');
    Route::get('estaca-escavada', fn() => view('es.estaca-escavada'))->name('estaca-escavada');
    Route::get('estrutura-metalica', fn() => view('es.estrutura-metalica'))->name('estrutura-metalica');
    Route::get('formulario-de-denuncia', fn() => view('es.formulario-de-denuncia'))->name('formulario-de-denuncia');
    Route::get('fundacoes', fn() => view('es.fundacoes'))->name('fundacoes');
    Route::get('gas-liquefeito-de-petroleo', fn() => view('es.gas-liquefeito-de-petroleo'))->name('gas-liquefeito-de-petroleo');
    Route::get('gases-medicinais', fn() => view('es.gases-medicinais'))->name('gases-medicinais');
    Route::get('granulometria-por-peneiramento', fn() => view('es.granulometria-por-peneiramento'))->name('granulometria-por-peneiramento');
    Route::get('granulometria-por-sedimentacao', fn() => view('es.granulometria-por-sedimentacao'))->name('granulometria-por-sedimentacao');
    Route::get('helice-continua', fn() => view('es.helice-continua'))->name('helice-continua');
    Route::get('hidrossanitarios', fn() => view('es.hidrossanitarios'))->name('hidrossanitarios');
    Route::get('home-support-solo-sondagens', fn() => view('es.home-support-solo-sondagens'))->name('home-support-solo-sondagens');
    Route::get('inclinometro', fn() => view('es.inclinometro'))->name('inclinometro');
    Route::get('index', fn() => view('es.index'))->name('index');
    Route::get('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a', fn() => view('es.intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a'))->name('intranet-1cfdc4af6dd3a0d020f9e231f93633835dc41e71d823fa8923ded8e1ba76eb3a');
    Route::get('intranet', fn() => view('es.intranet'))->name('intranet');
    Route::get('limite-de-liquidez', fn() => view('es.limite-de-liquidez'))->name('limite-de-liquidez');
    Route::get('limite-de-pasticidade', fn() => view('es.limite-de-pasticidade'))->name('limite-de-pasticidade');
    Route::get('logica-e-telefonia', fn() => view('es.logica-e-telefonia'))->name('logica-e-telefonia');
    Route::get('marcos-de-referencia', fn() => view('es.marcos-de-referencia'))->name('marcos-de-referencia');
    Route::get('massa-especifica-dos-graos', fn() => view('es.massa-especifica-dos-graos'))->name('massa-especifica-dos-graos');
    Route::get('mct-compactacao', fn() => view('es.mct-compactacao'))->name('mct-compactacao');
    Route::get('mct-pastilha', fn() => view('es.mct-pastilha'))->name('mct-pastilha');
    Route::get('medicao-de-ph-in-situ', fn() => view('es.medicao-de-ph-in-situ'))->name('medicao-de-ph-in-situ');
    Route::get('medidores-de-vazao', fn() => view('es.medidores-de-vazao'))->name('medidores-de-vazao');
    Route::get('missao-valores-e-objetivos', fn() => view('es.missao-valores-e-objetivos'))->name('missao-valores-e-objetivos');
    Route::get('monitoramento-e-seguranca', fn() => view('es.monitoramento-e-seguranca'))->name('monitoramento-e-seguranca');
    Route::get('pagina-1', fn() => view('es.pagina-1'))->name('pagina-1');
    Route::get('paisagismo', fn() => view('es.paisagismo'))->name('paisagismo');
    Route::get('piezometro', fn() => view('es.piezometro'))->name('piezometro');
    Route::get('plano-de-seguranca-do-trabalho', fn() => view('es.plano-de-seguranca-do-trabalho'))->name('plano-de-seguranca-do-trabalho');
    Route::get('poco-de-inspecao-de-pavimento', fn() => view('es.poco-de-inspecao-de-pavimento'))->name('poco-de-inspecao-de-pavimento');
    Route::get('poco-de-monitoramento', fn() => view('es.poco-de-monitoramento'))->name('poco-de-monitoramento');
    Route::get('politica-anticorrupcao', fn() => view('es.politica-anticorrupcao'))->name('politica-anticorrupcao');
    Route::get('politica-de-anti-assedio', fn() => view('es.politica-de-anti-assedio'))->name('politica-de-anti-assedio');
    Route::get('politica-de-assedio-moral', fn() => view('es.politica-de-assedio-moral'))->name('politica-de-assedio-moral');
    Route::get('politica-de-dados', fn() => view('es.politica-de-dados'))->name('politica-de-dados');
    Route::get('politica-de-gestao-ambiental', fn() => view('es.politica-de-gestao-ambiental'))->name('politica-de-gestao-ambiental');
    Route::get('politica-de-qualidade', fn() => view('es.politica-de-qualidade'))->name('politica-de-qualidade');
    Route::get('portfolio-servicos-geologicos', fn() => view('es.portfolio-servicos-geologicos'))->name('portfolio-servicos-geologicos');
    Route::get('portfolio-servicos-mineracao', fn() => view('es.portfolio-servicos-mineracao'))->name('portfolio-servicos-mineracao');
    Route::get('portfolio-servicos-transmissao', fn() => view('es.portfolio-servicos-transmissao'))->name('portfolio-servicos-transmissao');
    Route::get('resistividade-de-pe-de-torre', fn() => view('es.resistividade-de-pe-de-torre'))->name('resistividade-de-pe-de-torre');
    Route::get('resistividade-termica-do-solo', fn() => view('es.resistividade-termica-do-solo'))->name('resistividade-termica-do-solo');
    Route::get('retrofit-engenharia', fn() => view('es.retrofit-engenharia'))->name('retrofit-engenharia');
    Route::get('servicos-elaboracao-projetos', fn() => view('es.servicos-elaboracao-projetos'))->name('servicos-elaboracao-projetos');
    Route::get('servicos-fundacao-profunda', fn() => view('es.servicos-fundacao-profunda'))->name('servicos-fundacao-profunda');
    Route::get('servicos-geologico', fn() => view('es.servicos-geologico'))->name('servicos-geologico');
    Route::get('servicos-laboratorial', fn() => view('es.servicos-laboratorial'))->name('servicos-laboratorial');
    Route::get('sinalizacao', fn() => view('es.sinalizacao'))->name('sinalizacao');
    Route::get('som-tv-e-acustica', fn() => view('es.som-tv-e-acustica'))->name('som-tv-e-acustica');
    Route::get('sonda-de-polarizacao', fn() => view('es.sonda-de-polarizacao'))->name('sonda-de-polarizacao');
    Route::get('sonda-eletrica-focada', fn() => view('es.sonda-eletrica-focada'))->name('sonda-eletrica-focada');
    Route::get('sonda-gama-natural', fn() => view('es.sonda-gama-natural'))->name('sonda-gama-natural');
    Route::get('sonda-para-desvio-de-poco', fn() => view('es.sonda-para-desvio-de-poco'))->name('sonda-para-desvio-de-poco');
    Route::get('sonda-raio-gama', fn() => view('es.sonda-raio-gama'))->name('sonda-raio-gama');
    Route::get('sondagem-a-percussao', fn() => view('es.sondagem-a-percussao'))->name('sondagem-a-percussao');
    Route::get('sondagem-a-trado', fn() => view('es.sondagem-a-trado'))->name('sondagem-a-trado');
    Route::get('sondagem-eletrica-vertical', fn() => view('es.sondagem-eletrica-vertical'))->name('sondagem-eletrica-vertical');
    Route::get('sondagem-flutuante', fn() => view('es.sondagem-flutuante'))->name('sondagem-flutuante');
    Route::get('sondagem-manual', fn() => view('es.sondagem-manual'))->name('sondagem-manual');
    Route::get('sondagem-mista', fn() => view('es.sondagem-mista'))->name('sondagem-mista');
    Route::get('sondagem-rotativa', fn() => view('es.sondagem-rotativa'))->name('sondagem-rotativa');
    Route::get('sondagem-rotopercussiva', fn() => view('es.sondagem-rotopercussiva'))->name('sondagem-rotopercussiva');
    Route::get('sondagem-sondas-especiais', fn() => view('es.sondagem-sondas-especiais'))->name('sondagem-sondas-especiais');
    Route::get('spda', fn() => view('es.spda'))->name('spda');
    Route::get('speedy', fn() => view('es.speedy'))->name('speedy');
    Route::get('termo-de-servicos', fn() => view('es.termo-de-servicos'))->name('termo-de-servicos');
    Route::get('triaxial', fn() => view('es.triaxial'))->name('triaxial');
    Route::get('vane-test-ensaio-de-palheta', fn() => view('es.vane-test-ensaio-de-palheta'))->name('vane-test-ensaio-de-palheta');
    Route::get('visita-tecnica-engenharia', fn() => view('es.visita-tecnica-engenharia'))->name('visita-tecnica-engenharia');
});

// Keep existing admin routes and other application routes below
